version: 2
aliases:
- &post_build
  name: Trigger downstream builds
  command: |
    echo 'export CIRCLE_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV
    echo 'export CIRCLE_PROJECT_REPONAME="$CIRCLE_PROJECT_REPONAME"' >> $BASH_ENV
    echo 'export GITHUB_TOKEN="$GITHUB_TOKEN"' >> $BASH_ENV

    /tools/trigger_build.sh "entur/tiamat.git" "master" "$(git log -1 --pretty=%B)"
    /tools/trigger_build.sh "entur/anshar.git" "master" "$(git log -1 --pretty=%B)"
    /tools/trigger_build.sh "entur/baba.git" "master" "$(git log -1 --pretty=%B)"
    /tools/trigger_build.sh "entur/asag.git" "master" "$(git log -1 --pretty=%B)"
    /tools/trigger_build.sh "entur/chouette.git" "rutebanken_develop" "$(git log -1 --pretty=%B)"
    /tools/trigger_build.sh "entur/extime.git" "master" "$(git log -1 --pretty=%B)"
    /tools/trigger_build.sh "entur/kakka.git" "master" "$(git log -1 --pretty=%B)"
    /tools/trigger_build.sh "entur/namtar.git" "master" "$(git log -1 --pretty=%B)"
    /tools/trigger_build.sh "entur/uttu.git" "master" "$(git log -1 --pretty=%B)"
    /tools/trigger_build.sh "entur/opentripplanner.git" "rutebanken_develop" "$(git log -1 --pretty=%B)"
    /tools/trigger_build.sh "entur/opentripplanner.git" "entur_raptor" "$(git log -1 --pretty=%B)"
    /tools/trigger_build.sh "entur/opentripplanner.git" "entur_nordic" "$(git log -1 --pretty=%B)"
    # Marduk should be triggered from otp
    /tools/trigger_build.sh "entur/profile-norway-validation.git" "master" "$(git log -1 --pretty=%B)"
jobs:
  test:
    docker:
      - image: eu.gcr.io/carbon-1287/circleci-toolbox-image
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    environment:
      MAVEN_OPTS: -Xmx3G
    steps:
      - checkout
      - restore_cache:
          key: dep-cache-{{ checksum "pom.xml" }}
      - run: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.0:go-offline -s /tools/m2/settings.xml
      - save_cache:
          paths:
            - ~/.m2
          key: dep-cache-{{ checksum "pom.xml" }}
      # Cannot use -o because of snapshot dependencies.
      - run: mvn org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test -s /tools/m2/settings.xml
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
  build:
    docker:
    - image: eu.gcr.io/carbon-1287/circleci-toolbox-image
      auth:
        username: _json_key
        password: $GCLOUD_SERVICE_KEY
    environment:
      MAVEN_OPTS: -Xmx3G
    steps:
    - checkout
    - restore_cache:
        key: dep-cache-{{ checksum "pom.xml" }}
    - run: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.0:go-offline -s /tools/m2/settings.xml
    - save_cache:
        paths:
        - ~/.m2
        key: dep-cache-{{ checksum "pom.xml" }}
    # Cannot use -o because of snapshot dependencies.
    - run: mvn install -s /tools/m2/settings.xml -DskipTests
    - run:
        name: Save test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
        when: always
    - store_test_results:
        path: ~/junit
    - store_artifacts:
        path: ~/junit
  deploy:
    docker:
      - image: eu.gcr.io/carbon-1287/circleci-toolbox-image
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    environment:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - checkout
      - restore_cache:
          key: dep-cache-{{ checksum "pom.xml" }}
      - run:
          name: Maven deploy
          command: mvn deploy -s /tools/m2/settings.xml -DskipTests
      - run: *post_build
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test:
          context: org-carbon
      - build:
          context: org-carbon
          requires:
          - test
      - deploy:
          context: org-carbon
          requires:
            - build
          filters:
            branches:
              only: master