version: 2

aliases:
  - &sonar-scan
    name: Sonar scan
    command: |
      mvn -Psonar -s .circleci/settings.xml \
        sonar:sonar \
        -Dsonar.projectKey=entur_${CIRCLE_PROJECT_REPONAME} \
        -Dsonar.organization=${SONAR_ORG} \
        -Dsonar.projectName=${CIRCLE_PROJECT_REPONAME} \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${ENTUR_SONAR_PASSWORD}

jobs:
  test:
    docker:
      - image:  cimg/openjdk:11.0
    environment:
      MAVEN_OPTS: -Xmx3G
    steps:
      - checkout
      - restore_cache:
          key: dep-cache-{{ checksum "pom.xml" }}
      - run:
         name: Install xmlstarlet
         command: sudo apt-get -y install xmlstarlet
      - run:
          name: Download Maven settings
          command: wget https://raw.githubusercontent.com/entur/circleci-toolbox-image-java11/master/tools/m2/settings.xml -O .circleci/settings.xml
      - run:
          name: Refresh cache
          command: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.0:go-offline -s .circleci/settings.xml
      - save_cache:
          paths:
            - ~/.m2
          key: dep-cache-{{ checksum "pom.xml" }}
      # Cannot use -o because of snapshot dependencies.
      - run:
          name: Run Maven verify
          command: mvn verify -s .circleci/settings.xml
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - persist_to_workspace:
          root: ~/project
          paths:
            - target
            - .circleci

  sonar:
    docker:
      - image:  cimg/openjdk:11.0
    environment:
      MAVEN_OPTS: -Xmx3G
    steps:
      - checkout
      - restore_cache:
          key: dep-cache-{{ checksum "pom.xml" }}
      - attach_workspace:
          at: ~/project
      - run: *sonar-scan

  build:
    docker:
      - image:  cimg/openjdk:8.0
    environment:
      MAVEN_OPTS: -Xmx3G
    steps:
    - checkout
    - restore_cache:
        key: dep-cache-{{ checksum "pom.xml" }}
    - run:
         name: Install xmlstarlet
         command: sudo apt-get -y install xmlstarlet
    - run:
        name: Download Maven settings
        command: wget https://raw.githubusercontent.com/entur/circleci-toolbox-image-java11/master/tools/m2/settings.xml -O .circleci/settings.xml
    - run:
        name: Refresh cache
        command: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.0:go-offline -s .circleci/settings.xml
    - save_cache:
        paths:
        - ~/.m2
        key: dep-cache-{{ checksum "pom.xml" }}
    - run:
        name: Run Maven package
        command: mvn package -s .circleci/settings.xml -DskipTests
    - run:
  deploy:
    docker:
      - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image
        auth:
          username: _json_key
          password: $DOCKER_PASSWORD
    environment:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - checkout
      - restore_cache:
          key: dep-cache-{{ checksum "pom.xml" }}
      - run:
          name: Run Maven deploy
          command: mvn deploy -s .circleci/settings.xml -DskipTests
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test:
          context: org-carbon
      - sonar:
          context: org-carbon
          requires:
            - test
      - build:
          context: org-carbon
          requires:
          - sonar
      - deploy:
          context: org-carbon
          requires:
            - build
          filters:
            branches:
              only: master
